# .github/workflows/comment-run.yml
name: "Comment run"
on:
  issue_comment:
    types: [created, edited]

jobs:
  comment-run:
    runs-on: ubuntu-18.04
    steps:
#      - uses: actions/checkout@v2
#        with:
##           0 indicates all history
#          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: ls -a
      - run: node ../pr-bot/index.js
      - uses: nwtgck/actions-comment-run@v1.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          allowed-associations: '["OWNER", "MEMBER"]'
